# Generated by Django 6.0.5 on 2026-05-13 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('color_palette', models.JSONField(default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='GenreUnmapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=120, unique=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-hit_count'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('genres', models.JSONField(default=list)),
                ('primary_genre_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='core.genrebucket')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('tier', models.CharField(choices=[('shack', 'Shack'), ('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office'), ('skyscraper', 'Skyscraper'), ('landmark', 'Landmark')], default='shack', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='core.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-score'], name='core_artist_user_id_14d7ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'artist'), name='unique_artist_score_per_user')],
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=64)),
                ('played_at', models.DateTimeField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='core.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', 'artist', 'played_at'], name='core_playhi_user_id_da347c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'played_at', 'track_id'), name='unique_play_per_user_time_track')],
            },
        ),
        migrations.CreateModel(
            name='TierEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_tier', models.CharField(choices=[('shack', 'Shack'), ('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office'), ('skyscraper', 'Skyscraper'), ('landmark', 'Landmark')], max_length=20)),
                ('new_tier', models.CharField(choices=[('shack', 'Shack'), ('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office'), ('skyscraper', 'Skyscraper'), ('landmark', 'Landmark')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_events', to='core.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'delivered_at'], name='core_tierev_user_id_dc2fd3_idx')],
            },
        ),
    ]
