# Generated by Django 6.0.5 on 2026-05-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_genre_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistscore',
            name='seed_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistscore',
            name='seed_score',
            field=models.FloatField(default=0.0),
        ),
    ]
