# Generated by Django 6.0.5 on 2026-05-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_artistscore_seed_assigned_at_artistscore_seed_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistscore',
            name='last_played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
