# Generated by Django 6.0.5 on 2026-07-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_artistscore_last_played_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spotifyaccount',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
